### PR TITLE
Fixing the Port issue

### PR DESCRIPTION
**Pull request by htinaunglu**
So the original script call for the --rport argument, but the internal functions don't use the argument and only use the default port which is 80. This PR fixed this issue and now the user can assign any port where the webfig page of the router is open. 

~~Also added requirements.txt for easy deploying!~~

### CODE REVIEW

**Comment by htinaunglu** [comment]
@j-baines any comments?

**Comment by j-baines** [comment]
Thanks! I appreciate the port fix.

The `requirements.txt` is quite a bit more restrictive than I'd like (e.g. I'm not using `certifi==2023.7.22` - I think I'm using a 2019 version). I'd happily merge this without the `requirements.txt` file.

**Comment by htinaunglu** [comment]
This is nice! Thank you for merging Jacob! I will close it now!

**Comment by htinaunglu** [comment]
Sorry, my bad, thought it was merged! xD. I will now reopen with `requirements.txt` excluded!

**Comment by j-baines** [comment]
Thanks @htinaunglu !

**Pull request merged**
